### ISSUE TITLE
Sidebar: Hide on mobile Issue.

### ISSUE THREAD

**Issue by JamesNuttall** [surevine/simple-social-buttons#1]
I've noticed that when selecting "Hide on Mobile" for the sidebar section, it isn't actually hiding the sidebar, it still displays.

**Comment by ashward** [comment]
I'm afraid this is a very old and entirely unmaintained fork of the original project! You might want to look at the maintained version here: https://wordpress.org/plugins/simple-social-buttons/
If the issue is with the current version then raise it here: https://wordpress.org/support/plugin/simple-social-buttons
